set -x

ray job submit --address="http://127.0.0.1:8265" \
    --runtime-env-json='{"working_dir": ".", "excludes": ["*.log"]}' \
    -- python3 -m openrlhf.cli.train_ppo_ray \
    --ref_num_nodes 1 \
    --ref_num_gpus_per_node 4 \
    --actor_num_nodes 1 \
    --actor_num_gpus_per_node 4 \
    --vllm_num_engines 4 \
    --vllm_tensor_parallel_size 1 \
    --colocate_actor_ref \
    --save_steps 20 \
    --lr_warmup_ratio 0.01 \
    --pretrain ./checkpoint/Llama-3_2-3B-sft \
    --save_path ./checkpoint/Llama-3_2-3B-grpo \
    --ckpt_path ./checkpoint/Llama-3_2-3B-grpo-ckpt \
    --save_hf_ckpt \
    --load_checkpoint \
    --save_grader_result_path ./training_output/Llama-3_2-3B-grpo/grader_result.jsonl \
    --save_rollout_path ./training_output/Llama-3_2-3B-grpo/rollout \
    --remote_rm_url ./thinkfl/reward_func.py \
    --micro_train_batch_size 1 \
    --train_batch_size 8 \
    --micro_rollout_batch_size 1 \
    --rollout_batch_size 16 \
    --num_episodes 1 \
    --max_epochs 1 \
    --prompt_max_len 3000 \
    --generate_max_len 5000 \
    --advantage_estimator group_norm \
    --n_samples_per_prompt 4 \
    --zero_stage 2 \
    --bf16 \
    --actor_learning_rate 5e-7 \
    --init_kl_coef 1e-3 \
    --gamma 1.0 \
    --use_kl_loss \
    --kl_estimator k3 \
    --temperature 0.3 \
    --prompt_data ./dataset_mix \
    --input_key context_messages \
    --apply_chat_template \
    --max_samples 20000 \
    --normalize_reward \
    --adam_offload \
    --flash_attn \
    --vllm_sync_backend nccl \
    --gradient_checkpointing \
    --enforce_eager \
    --vllm_enable_sleep \
    --deepspeed_enable_sleep \
    --use_wandb True \
    --wandb_host "${WANDB_HOST:-https://api.wandb.ai}" \
    --wandb_api_key "$WANDB_API_KEY"
